create table cliente (
                         id bigint generated by default as identity,
                         email varchar(255) not null,
                         foto varchar(255),
                         idade integer check (idade>=0),
                         nome varchar(255) not null,
                         sobrenome varchar(255) not null,
                         primary key (id)
);

create table produto (
                         id bigint generated by default as identity,
                         data_atualizado timestamp(6),
                         descricao varchar(255),
                         nome varchar(255) not null,
                         preco float(53),
                         primary key (id)
);


INSERT INTO CLIENTE (nome, sobrenome, email, idade, foto) VALUES
                                                              ('Ana', 'Oliveira', 'ana.oliveira@example.com', 34, NULL),
                                                              ('Carlos', 'Santos', 'carlos.santos@example.com', 29, NULL),
                                                              ('Beatriz', 'Costa', 'beatriz.costa@example.com', 27, NULL),
                                                              ('Diego', 'Pereira', 'diego.pereira@example.com', 41, NULL),
                                                              ('Eduarda', 'Almeida', 'eduarda.almeida@example.com', 25, NULL),
                                                              ('Felipe', 'Ribeiro', 'felipe.ribeiro@example.com', 38, NULL),
                                                              ('Gabriela', 'Lima', 'gabriela.lima@example.com', 31, NULL),
                                                              ('Henrique', 'Gomes', 'henrique.gomes@example.com', 45, NULL),
                                                              ('Isabela', 'Martins', 'isabela.martins@example.com', 22, NULL),
                                                              ('João Pedro', 'Ferreira', 'joao.pedro@example.com', 19, NULL),
                                                              ('Larissa', 'Rodrigues', 'larissa.rodrigues@example.com', 33, NULL),
                                                              ('Lucas', 'Nascimento', 'lucas.nascimento@example.com', 26, NULL),
                                                              ('Mariana', 'Barbosa', 'mariana.barbosa@example.com', 30, NULL),
                                                              ('Natália', 'Cardoso', 'natalia.cardoso@example.com', 28, NULL),
                                                              ('Otávio', 'Mendes', 'otavio.mendes@example.com', 52, NULL),
                                                              ('Paula', 'Freitas', 'paula.freitas@example.com', 24, NULL),
                                                              ('Rafael', 'Carvalho', 'rafael.carvalho@example.com', 37, NULL),
                                                              ('Sofia', 'Araújo', 'sofia.araujo@example.com', 21, NULL),
                                                              ('Thiago', 'Duarte', 'thiago.duarte@example.com', 40, NULL),
                                                              ('Vitória', 'Monteiro', 'vitoria.monteiro@example.com', 29, NULL);

INSERT INTO PRODUTO (nome, descricao, preco, data_atualizado) VALUES
                                                                  ('Mouse Gamer RGB', 'Mouse 12000 DPI com 7 botões programáveis', 219.90, CURRENT_TIMESTAMP),
                                                                  ('Teclado Mecânico', 'Switch Blue, retroiluminado RGB', 379.00, CURRENT_TIMESTAMP),
                                                                  ('Fone Bluetooth JBL', 'Cancelamento de ruído ativo, 30h bateria', 489.90, CURRENT_TIMESTAMP),
                                                                  ('Cabo USB-C 2m', 'Suporte a carregamento rápido 100W', 49.90, CURRENT_TIMESTAMP),
                                                                  ('Webcam Full HD 1080p', 'Com microfone estéreo e tripé', 299.00, CURRENT_TIMESTAMP),
                                                                  ('Monitor 24" IPS', '75Hz, bordas finas, HDMI + VGA', 899.90, CURRENT_TIMESTAMP),
                                                                  ('SSD 1TB NVMe', 'Leitura até 3500MB/s', 489.00, CURRENT_TIMESTAMP),
                                                                  ('Pen Drive 128GB', 'USB 3.0, velocidade 150MB/s', 89.90, CURRENT_TIMESTAMP),
                                                                  ('Carregador GaN 65W', '3 portas (2 USB-C + 1 USB-A)', 189.90, CURRENT_TIMESTAMP),
                                                                  ('Suporte Notebook', 'Ajustável em alumínio com ventilação', 139.90, CURRENT_TIMESTAMP),
                                                                  ('Caixa de Som 20W', 'Bluetooth 5.0, à prova d´água IPX7', 229.90, CURRENT_TIMESTAMP),
                                                                  ('Hub USB 7 portas', 'USB 3.0 com chave individual', 119.90, CURRENT_TIMESTAMP),
                                                                  ('Tapete Mouse XXL', '900x400mm Speed Edition', 79.90, CURRENT_TIMESTAMP),
                                                                  ('Headset Gamer', 'Som 7.1, microfone retrátil', 349.90, CURRENT_TIMESTAMP),
                                                                  ('Adaptador USB-C para HDMI', 'Suporte 4K 60Hz', 99.90, CURRENT_TIMESTAMP),
                                                                  ('Bateria Externa 20000mAh', 'Power Delivery 45W', 219.90, CURRENT_TIMESTAMP),
                                                                  ('Lâmpada Smart Wi-Fi', '16 milhões de cores, compatível Alexa/Google', 89.90, CURRENT_TIMESTAMP),
                                                                  ('Controle Xbox Series', 'Original Microsoft Branco', 429.90, CURRENT_TIMESTAMP),
                                                                  ('Cadeira Gamer', 'Reclinável 180°, apoio lombar', 1199.90, CURRENT_TIMESTAMP),
                                                                  ('Mini Projetor LED', '8000 lumens, Wi-Fi Mirror', 899.90, CURRENT_TIMESTAMP);
